global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["192.168.4.125:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["192.168.4.125:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["192.168.4.125:8081"]
